name: Push (Build Test)
on: [push]


jobs:
  build-test:
    uses: neilotoole/sqlitr2/.github/workflows/build-test.yml@master
#  build-test:
#    strategy:
#      matrix:
#        os: [ macos-12, ubuntu-22.04, windows-2022]
#
#    runs-on: ${{ matrix.os }}
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: 1.19
#
#      - name: Build
#        run: go build -v ./...
#
#      - name: Test
#        run: go test -v -race ./...

#
#  build-artifacts-macos:
#    needs: build-test
#    runs-on: macos-12
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: 1.19
#
#      - name: Run GoReleaser
#        uses: goreleaser/goreleaser-action@v3
#        with:
#          # either 'goreleaser' (default) or 'goreleaser-pro'
#          distribution: goreleaser-pro
#          version: 1.12.3
#          args: release --rm-dist -f .goreleaser-macos.yml
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
#          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
#
#      - name: Upload assets
#        uses: actions/upload-artifact@v3
#        with:
#          name: sqlitr2
#          path: dist/*
